In [ ]:
pip install numpy

In [ ]:
import numpy as np

In [ ]:
a = [1,2,3,4,5]
a

[1, 2, 3, 4, 5]

In [ ]:
arr1 = np.array(a)
arr1

array([1, 2, 3, 4, 5])

In [ ]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr3 = np.array([[[1,2,3,4],[44,5,6,7]],[[1,3,6,7],[4,5,6,7]]])
arr3

array([[[ 1,  2,  3,  4],
        [44,  5,  6,  7]],

       [[ 1,  3,  6,  7],
        [ 4,  5,  6,  7]]])

In [ ]:
np.full((3,4),2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
type(arr2)

numpy.ndarray

In [ ]:
arr1.shape

(5,)

In [ ]:
arr2.shape

(2, 3)

In [ ]:
arr3.shape

(2, 2, 4)

In [ ]:
arr1[4]

5

In [ ]:
arr1[-1]

5

In [ ]:
arr1

array([1, 2, 3, 4, 5])

In [ ]:
arr1[2:4]

array([3, 4])

In [ ]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2[1,1]

5

In [ ]:
arr2[1,2]

6

In [ ]:
arr2[:]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2[:,-1]

array([3, 6])

In [ ]:
arr3[0,:,1]  ### matrix number, row, column

array([2, 5])

In [ ]:
arr3

array([[[ 1,  2,  3,  4],
        [44,  5,  6,  7]],

       [[ 1,  3,  6,  7],
        [ 4,  5,  6,  7]]])

In [ ]:
arr3[1,:,2:4]

array([[6, 7],
       [6, 7]])

In [ ]:
np.random.random((3,4))  ## outter bracket is for function , inner braccet is for dimension

array([[0.22141454, 0.8497354 , 0.78487125, 0.45549986],
       [0.95887032, 0.252148  , 0.24415473, 0.27413893],
       [0.95588576, 0.84136225, 0.59728367, 0.75340662]])

In [ ]:
np.full((3,3,4),10)

array([[[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]],

       [[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]],

       [[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.eye((4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
Mat1 = np.array([[1,2,3],[2,4,6]])
Mat2 = np.array([[2,4,1],[2,3,23]])

Mat3= Mat1+Mat2

print(Mat1,Mat2, Mat3)


[[1 2 3]
 [2 4 6]] [[ 2  4  1]
 [ 2  3 23]] [[ 3  6  4]
 [ 4  7 29]]


In [ ]:
Mat3

array([[ 3,  6,  4],
       [ 4,  7, 29]])

In [ ]:
Mat4 = np.array([[1,2],[2,3],[4,5]])
Mat4

array([[1, 2],
       [2, 3],
       [4, 5]])

In [ ]:
Mat1*Mat2

array([[  2,   8,   3],
       [  4,  12, 138]])

In [ ]:
Mat1*Mat4.T

array([[ 1,  4, 12],
       [ 4, 12, 30]])

In [ ]:
Mat1

array([[1, 2, 3],
       [2, 4, 6]])

In [ ]:
np.linspace(-90,90,180)

array([-90.        , -88.99441341, -87.98882682, -86.98324022,
       -85.97765363, -84.97206704, -83.96648045, -82.96089385,
       -81.95530726, -80.94972067, -79.94413408, -78.93854749,
       -77.93296089, -76.9273743 , -75.92178771, -74.91620112,
       -73.91061453, -72.90502793, -71.89944134, -70.89385475,
       -69.88826816, -68.88268156, -67.87709497, -66.87150838,
       -65.86592179, -64.8603352 , -63.8547486 , -62.84916201,
       -61.84357542, -60.83798883, -59.83240223, -58.82681564,
       -57.82122905, -56.81564246, -55.81005587, -54.80446927,
       -53.79888268, -52.79329609, -51.7877095 , -50.78212291,
       -49.77653631, -48.77094972, -47.76536313, -46.75977654,
       -45.75418994, -44.74860335, -43.74301676, -42.73743017,
       -41.73184358, -40.72625698, -39.72067039, -38.7150838 ,
       -37.70949721, -36.70391061, -35.69832402, -34.69273743,
       -33.68715084, -32.68156425, -31.67597765, -30.67039106,
       -29.66480447, -28.65921788, -27.65363128, -26.64

In [ ]:
x2 = np.random.randint(10, size = (3,4))

In [ ]:
x2

array([[4, 3, 7, 7],
       [3, 7, 4, 5],
       [8, 1, 4, 9]])

In [ ]:
x3 = np.random.randint(5, size = (3,3,4))
x3

array([[[4, 2, 3, 1],
        [0, 0, 1, 4],
        [0, 1, 1, 2]],

       [[4, 0, 1, 4],
        [4, 1, 1, 2],
        [1, 2, 0, 3]],

       [[4, 2, 4, 3],
        [1, 4, 4, 1],
        [2, 4, 3, 3]]])

In [12]:
import numpy as np
x=np.array([[1,2,3],[2,4,6],[7,8,9],[9,10,11]])
x

array([[ 1,  2,  3],
       [ 2,  4,  6],
       [ 7,  8,  9],
       [ 9, 10, 11]])